VPATH+=$(SRC_PATH)/tests/tcg/s390x
CFLAGS+=-march=zEC12 -m64
TESTS+=hello-s390x
TESTS+=csst
TESTS+=ipm
TESTS+=exrl-trt
TESTS+=exrl-trtr
TESTS+=pack
TESTS+=mvo
TESTS+=mvc

VECTOR_TESTS=vge
VECTOR_TESTS+=vlgv
VECTOR_TESTS+=vgbm
VECTOR_TESTS+=vgm
VECTOR_TESTS+=vlrep
VECTOR_TESTS+=vmr
VECTOR_TESTS+=vpk
VECTOR_TESTS+=vup
VECTOR_TESTS+=va
VECTOR_TESTS+=vsel
VECTOR_TESTS+=verll
VECTOR_TESTS+=vsum
VECTOR_TESTS+=vm
VECTOR_TESTS+=vsl
VECTOR_TESTS+=vceq
VECTOR_TESTS+=vs
TESTS+=$(VECTOR_TESTS)

#enable vectors and optimisation for vector tests
$(VECTOR_TESTS): CFLAGS+=-march=z13 -O2
